name: DevSecOps Azure IaC Scan

permissions:
  contents: read
  security-events: write 
  actions: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Security Scan (SARIF Output)
        id: checkov
        run: checkov -d . --output sarif > checkov-results.sarif
        continue-on-error: true

      - name: Upload SARIF file to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif